name: Rust Cross-Compilation and Artifact Upload

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - riscv64gc-unknown-linux-gnu
          - powerpc64le-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3

      - name: Install cross
        run: cargo install cross --force

      - name: Build for ${{ matrix.target }}
        run: cross build --release --target ${{ matrix.target }}

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: dangergame-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/dangergame

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build for x86_64-pc-windows-msvc
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: dangergame-x86_64-pc-windows-msvc
          path: target/x86_64-pc-windows-msvc/release/dangergame.exe
