name: Build game

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Linux x86_64
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - uses: actions/upload-artifact@v4
        with:
          name: dangergame-linux-x86_64
          path: target/x86_64-unknown-linux-gnu/release/dangergame

  build-linux-arm64:
    runs-on: ubuntu-latest-arm64
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Linux ARM64
        run: cargo build --release --target aarch64-unknown-linux-gnu

      - uses: actions/upload-artifact@v4
        with:
          name: dangergame-linux-arm64
          path: target/aarch64-unknown-linux-gnu/release/dangergame

  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build macOS ARM64
        run: cargo build --release --target aarch64-apple-darwin

      - uses: actions/upload-artifact@v4
        with:
          name: dangergame-macos-arm64
          path: target/aarch64-apple-darwin/release/dangergame

  build-windows-x86_64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Windows x86_64
        run: cargo build --release --target x86_64-pc-windows-msvc

      - uses: actions/upload-artifact@v4
        with:
          name: dangergame-windows-x86_64
          path: target\x86_64-pc-windows-msvc\release\dangergame.exe
